/**
 * Constantes de las acciones
 */

const ADD_CONTACT = "ADD_CONTACT";
const SEARCH_CONTACT = "SEARCH_CONTACT";
const REMOVE_CONTACT = "REMOVE_CONTACT";
const SHOW_CONTACT_LIST = "SHOW_CONTACT_LIST";
const OPEN_MODAL_FORM = "OPEN_MODAL_FORM";

export {
  ADD_CONTACT,
  SEARCH_CONTACT,
  REMOVE_CONTACT,
  SHOW_CONTACT_LIST,
  OPEN_MODAL_FORM
};
